version: "3.9"

name: flyingcloud-stack

networks:
  default:
    name: ${NET}
    external: false

services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CTN}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASS}
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --max_connections=300
      --general-log=ON
      --slow_query_log=ON
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_CONF_DIR}:/etc/mysql/conf.d
      - ${MYSQL_INIT_DIR}:/docker-entrypoint-initdb.d
      - ${SQL_FILE}:/docker-entrypoint-initdb.d/99_ledger_flow.sql:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -p${DB_ROOT_PASS} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_CTN}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    command: >
      redis-server
      --requirepass ${REDIS_PASS}
      --appendonly yes
      --maxmemory-policy allkeys-lru
    volumes:
      - ${REDIS_DATA_DIR}:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy

  app:
    build:
      context: ${PROJECT_DIR}
      dockerfile: Dockerfile
    image: ${APP_IMG}
    container_name: ${APP_CTN}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      SERVER_PORT: ${SERVER_PORT}
      DB_URL: jdbc:mysql://mysql:3306/${DB}?useSSL=false&serverTimezone=${TZ}&characterEncoding=utf8&allowPublicKeyRetrieval=true
      DB_USER: ${APP_DB_USER}
      DB_PASS: ${APP_DB_PASS}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASS}
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75 -Dfile.encoding=UTF-8"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/${SERVER_PORT} && exec 3>&-'"]
      interval: 30s
      timeout: 3s
      retries: 10